name: prayer_book
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  fluro: ^2.0.5
  get_it: ^8.0.3
  flutter_bloc: ^8.1.6
  injectable: ^2.5.0
  shared_preferences: ^2.3.4
  flutter_localization: ^0.3.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator:
  build_runner:

flutter:
  uses-material-design: true
  generate: true
